### ISSUE TITLE
Multiple versions

### ISSUE THREAD

**Issue by electrocoder** [littlepea/django-docs#13]
Hi. We have 0.0.1 and 0.02 versions.  How to manage multiple versions of documentation with django-docs Sphinx?

**Comment by littlepea** [comment]
Hi @electrocoder .

The only thing that django-docs really does is serve a static folder (presumably generated by Sphinx) through Django with optional auth. It doesn't actually interact with Sphinx in any way, it just assumes you've already built the Shinx docs.

So if your Sphinx build already has the docs for multiple versions built it should work. How to do it though, I don't know, that's a Sphinx question.

**Comment by electrocoder** [comment]
Thanks @littlepea
