### ISSUE TITLE
NoReverseMatch

### ISSUE THREAD

**Issue by gthieleb** [littlepea/django-docs#14]
Exception:

> NoReverseMatch at /

> Reverse for 'docs' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Using url  in template:

	<a href="{% url 'docs' %}"><h3>Documentation</h3></a>

urls.py:

    url(r'^$', TemplateView.as_view(template_name='webdisplay/start.html'), name='start'),
    url(r'^docs/', include('docs.urls'), name='docs'),

Access via direct link works ok:

    http://localhost:8000/docs/index.html

**Comment by derekjamescurtis** [comment]
I realize this was a long time ago, but you'd want to have a look [here](https://github.com/littlepea/django-docs/blob/master/docs/urls.py).

I think what you'd actually want is:

```
<a href="{% url 'docs_root' %}"> ... </a>
```
