### ISSUE TITLE
multiple projects support

### ISSUE THREAD

**Issue by bioinfer** [littlepea/django-docs#15]
Hi, Do you plan to support multiple projects ?

**Comment by littlepea** [comment]
@bioinfer You mean multiple sphinx sources? Can you provide a usage example that would need to be supported? (`urls.py/settings.py`)

**Comment by bioinfer** [comment]
Thanks for your reply.

Suppose I have two projects, documentation of each project is written in sphinx-doc, I want hosting these documentation on django-docs, like this:

index.html
```html
<ul id="project_list">
    <li><a href="url-to-project-1-index">project 1</a></li>
    <li><a href="url-to-project-2-index"></a>project 2</li>
</ul>
```

when I click `project 1`, it redirect to project 1's documentation, etc.

**Comment by littlepea** [comment]
I see, so maybe what you're talking about could be implemented by supporting the following settings structure?

```
DOCS_DIRS = {
    'project1': os.path.join(PROJECT1_PATH, '../docs/_build/html'),
    'project2': os.path.join(PROJECT2_PATH, '../docs/_build/html'),
}
```

Right now it's not supported and could possibly be a feature in the future if it's useful. But at this point, django-docs doesn't really do anything other than serving a static folder with html/css files (presumably generated by sphinx) and optionally manages access rules for it, so you could just symlink multiple build directories of different shinx docs into one place and then use that directory as `DOCS_ROOT`

I think supporting "multiple projects" is an overkill for this app as it doesn't really know anything about "projects"...

**Comment by bioinfer** [comment]
OK, I see.
