### ISSUE TITLE
using django-docs with django 2.0

### ISSUE THREAD

**Issue by lukruh** [littlepea/django-docs#19]
I installed django-docs via pip3 such as mentioned in the readme.md but getting an import error:
```
No module named 'django.core.urlresolvers'
```
I guess this is caused by the change of this library from django.core.urlresovers to django.urls, where also other changes has taken place. Before I dive Into this modules code I want to ask if django2 is (going to be) supported by this modul otherwise i'll look for another way. Cannot waste too much time on hacking around with documentation serving.

**Comment by lukruh** [comment]
I swichted the import line in python3.5/dist-packages/docs/views.py
 
```
# from django.core.urlresolvers
from django.urls import reverse 
```

the import error seems to be gone but donno if there are other problems following..

**Comment by SultanSGillani** [comment]
I don't think this repo is maintained anymore.

However after updating the import line, I have forked the repository and was able to continually use this in Django 2.0.

I have not encountered any issues since.

**Comment by SultanSGillani** [comment]
This doesn’t seem to be an issue anymore.

**Comment by derekjamescurtis** [comment]
@sarbot this repository has been updated to support Django 2.0+.  It is now on pypi as version [0.3.0](https://pypi.org/project/django-docs/0.3.0/). Thanks @TheSaltman!
