### ISSUE TITLE
Update Django-docs on PyPy

### ISSUE THREAD

**Issue by SultanSGillani** [littlepea/django-docs#22]
Hey, is there any way you can update pypy so we can install this using pip?

Also most of the issues with Django 2.0 seem to be resolved which means many of the issues currently can be closed.

**Comment by derekjamescurtis** [comment]
@TheSaltman Your pull request is on pypi now as version [0.3.0](https://pypi.org/project/django-docs/0.3.0/).  Thanks!

**Comment by SultanSGillani** [comment]
yayy thanks!!!!
