### ISSUE TITLE
ulrpatterns update

### ISSUE THREAD

**Issue by firestalk** [littlepea/django-docs#3]
after checking my project by "manage.py check" I've found this warning

/usr/local/lib/python2.7/dist-packages/docs/urls.py:6: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^(?P<path>.*)$', serve_docs, name='docs_files'),

resolution - https://docs.djangoproject.com/en/1.9/ref/urls/#django.conf.urls.url

Using django 1.8 and 1.9

**Comment by littlepea** [comment]
Fixed
