### ISSUE TITLE
“/docs/_build/html/index.html” does not exist

### ISSUE THREAD

**Issue by giorgiberia** [littlepea/django-docs#30]
i followed steps do i need to generate sphinx docs from sphinx tool before this package serves it?
because now it says does not exist?

**Comment by littlepea** [comment]
Yes, this package is basically just a tool to serve a static directory behind django permissions check, that's all. It can actually be anything, not only Sphinx and even docs.

So yes, you have to handle all the Sphinx stuff yourself upfront.
