### ISSUE TITLE
can I serve multiple _build directories?

### ISSUE THREAD

**Issue by jsmedmar** [littlepea/django-docs#5]
I have a bunch of projects. Each of them uses sphinx, I'd like to serve their documentation in my django application. Is this project suited for such use case?

**Comment by littlepea** [comment]
I guess you can if you customize your build accordingly, this setting just points to a static directory to serve:

```
DOCS_ROOT = os.path.join(PROJECT_PATH, '../docs/_build/html')
```

So you can combine all your build `html` dirs to one place and point to it.

I've never done it this way, but you can give it a try.
