### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by littlepea** [littlepea/django-docs#9]
Need to update the `tox.ini` to have:

```
envlist = {py27,py35}-django{18,110,-trunk}
```

And make it pass...

**Comment by mounirmesselmeni** [comment]
@littlepea  Any news about this?

**Comment by SultanSGillani** [comment]
Tox passes all tests now except for testing python 2.7 against Django 2.0.

**Comment by derekjamescurtis** [comment]
Now updated on pypi.  https://pypi.org/project/django-docs/0.3.0/
